/*/ 

This header contains enumerations of Nations to use in C++ contracts for WAX blockchain.

Enums are explicitly numbered to maintain cross-contract compatibility if a person were to update this list. i.e. removing an unsupported country

/*/

enum class Countries_ISO3 {
    AFG = 4,    // Afghanistan
    ALA = 248,  // Åland Islands
    ALB = 8,    // Albania
    DZA = 12,   // Algeria
    ASM = 16,   // American Samoa
    AND = 20,   // Andorra
    AGO = 24,   // Angola
    AIA = 660,  // Anguilla
    ATA = 10,   // Antarctica
    ATG = 28,   // Antigua and Barbuda
    ARG = 32,   // Argentina
    ARM = 51,   // Armenia
    ABW = 533,  // Aruba
    AUS = 36,   // Australia
    AUT = 40,   // Austria
    AZE = 31,   // Azerbaijan
    BHS = 44,   // Bahamas
    BHR = 48,   // Bahrain
    BGD = 50,   // Bangladesh
    BRB = 52,   // Barbados
    BLR = 112,  // Belarus
    BEL = 56,   // Belgium
    BLZ = 84,   // Belize
    BEN = 204,  // Benin
    BMU = 60,   // Bermuda
    BTN = 64,   // Bhutan
    BOL = 68,   // Bolivia (Plurinational State of)
    BES = 535,  // Bonaire, Sint Eustatius and Saba
    BIH = 70,   // Bosnia and Herzegovina
    BWA = 72,   // Botswana
    BVT = 74,   // Bouvet Island
    BRA = 76,   // Brazil
    IOT = 86,   // British Indian Ocean Territory
    VGB = 92,   // British Virgin Islands
    BRN = 96,   // Brunei Darussalam
    BGR = 100,  // Bulgaria
    BFA = 854,  // Burkina Faso
    BDI = 108,  // Burundi
    CPV = 132,  // Cabo Verde
    KHM = 116,  // Cambodia
    CMR = 120,  // Cameroon
    CAN = 124,  // Canada
    CYM = 136,  // Cayman Islands
    CAF = 140,  // Central African Republic
    TCD = 148,  // Chad
    CHL = 152,  // Chile
    CHN = 156,  // China
    HKG = 344,  // China, Hong Kong Special Administrative Region
    MAC = 446,  // China, Macao Special Administrative Region
    CXR = 162,  // Christmas Island
    CCK = 166,  // Cocos (Keeling) Islands
    COL = 170,  // Colombia
    COM = 174,  // Comoros
    COG = 178,  // Congo
    COK = 184,  // Cook Islands
    CRI = 188,  // Costa Rica
    CIV = 384,  // Côte d'Ivoire
    HRV = 191,  // Croatia
    CUB = 192,  // Cuba
    CUW = 531,  // Curaçao
    CYP = 196,  // Cyprus
    CZE = 203,  // Czechia
    PRK = 408,  // Democratic People's Republic of Korea
    COD = 180,  // Democratic Republic of the Congo
    DNK = 208,  // Denmark
    DJI = 262,  // Djibouti
    DMA = 212,  // Dominica
    DOM = 214,  // Dominican Republic
    ECU = 218,  // Ecuador
    EGY = 818,  // Egypt
    SLV = 222,  // El Salvador
    GNQ = 226,  // Equatorial Guinea
    ERI = 232,  // Eritrea
    EST = 233,  // Estonia
    SWZ = 748,  // Eswatini
    ETH = 231,  // Ethiopia
    FLK = 238,  // Falkland Islands (Malvinas)
    FRO = 234,  // Faroe Islands
    FJI = 242,  // Fiji
    FIN = 246,  // Finland
    FRA = 250,  // France
    GUF = 254,  // French Guiana
    PYF = 258,  // French Polynesia
    ATF = 260,  // French Southern Territories
    GAB = 266,  // Gabon
    GMB = 270,  // Gambia
    GEO = 268,  // Georgia
    DEU = 276,  // Germany
    GHA = 288,  // Ghana
    GIB = 292,  // Gibraltar
    GRC = 300,  // Greece
    GRL = 304,  // Greenland
    GRD = 308,  // Grenada
    GLP = 312,  // Guadeloupe
    GUM = 316,  // Guam
    GTM = 320,  // Guatemala
    GGY = 831,  // Guernsey
    GIN = 324,  // Guinea
    GNB = 624,  // Guinea-Bissau
    GUY = 328,  // Guyana
    HTI = 332,  // Haiti
    HMD = 334,  // Heard Island and McDonald Islands
    VAT = 336,  // Holy See
    HND = 340,  // Honduras
    HUN = 348,  // Hungary
    ISL = 352,  // Iceland
    IND = 356,  // India
    IDN = 360,  // Indonesia
    IRN = 364,  // Iran (Islamic Republic of)
    IRQ = 368,  // Iraq
    IRL = 372,  // Ireland
    IMN = 833,  // Isle of Man
    ISR = 376,  // Israel
    ITA = 380,  // Italy
    JAM = 388,  // Jamaica
    JPN = 392,  // Japan
    JEY = 832,  // Jersey
    JOR = 400,  // Jordan
    KAZ = 398,  // Kazakhstan
    KEN = 404,  // Kenya
    KIR = 296,  // Kiribati
    KWT = 414,  // Kuwait
    KGZ = 417,  // Kyrgyzstan
    LAO = 418,  // Lao People's Democratic Republic
    LVA = 428,  // Latvia
    LBN = 422,  // Lebanon
    LSO = 426,  // Lesotho
    LBR = 430,  // Liberia
    LBY = 434,  // Libya
    LIE = 438,  // Liechtenstein
    LTU = 440,  // Lithuania
    LUX = 442,  // Luxembourg
    MDG = 450,  // Madagascar
    MWI = 454,  // Malawi
    MYS = 458,  // Malaysia
    MDV = 462,  // Maldives
    MLI = 466,  // Mali
    MLT = 470,  // Malta
    MHL = 584,  // Marshall Islands
    MTQ = 474,  // Martinique
    MRT = 478,  // Mauritania
    MUS = 480,  // Mauritius
    MYT = 175,  // Mayotte
    MEX = 484,  // Mexico
    FSM = 583,  // Micronesia (Federated States of)
    MCO = 492,  // Monaco
    MNG = 496,  // Mongolia
    MNE = 499,  // Montenegro
    MSR = 500,  // Montserrat
    MAR = 504,  // Morocco
    MOZ = 508,  // Mozambique
    MMR = 104,  // Myanmar
    NAM = 516,  // Namibia
    NRU = 520,  // Nauru
    NPL = 524,  // Nepal
    NLD = 528,  // Netherlands (Kingdom of the)
    NCL = 540,  // New Caledonia
    NZL = 554,  // New Zealand
    NIC = 558,  // Nicaragua
    NER = 562,  // Niger
    NGA = 566,  // Nigeria
    NIU = 570,  // Niue
    NFK = 574,  // Norfolk Island
    MKD = 807,  // North Macedonia
    MNP = 580,  // Northern Mariana Islands
    NOR = 578,  // Norway
    OMN = 512,  // Oman
    PAK = 586,  // Pakistan
    PLW = 585,  // Palau
    PAN = 591,  // Panama
    PNG = 598,  // Papua New Guinea
    PRY = 600,  // Paraguay
    PER = 604,  // Peru
    PHL = 608,  // Philippines
    PCN = 612,  // Pitcairn
    POL = 616,  // Poland
    PRT = 620,  // Portugal
    PRI = 630,  // Puerto Rico
    QAT = 634,  // Qatar
    KOR = 410,  // Republic of Korea
    MDA = 498,  // Republic of Moldova
    REU = 638,  // Réunion
    ROU = 642,  // Romania
    RUS = 643,  // Russian Federation
    RWA = 646,  // Rwanda
    BLM = 652,  // Saint Barthélemy
    SHN = 654,  // Saint Helena
    KNA = 659,  // Saint Kitts and Nevis
    LCA = 662,  // Saint Lucia
    MAF = 663,  // Saint Martin (French Part)
    SPM = 666,  // Saint Pierre and Miquelon
    VCT = 670,  // Saint Vincent and the Grenadines
    WSM = 882,  // Samoa
    SMR = 674,  // San Marino
    STP = 678,  // Sao Tome and Principe
    SAU = 682,  // Saudi Arabia
    SEN = 686,  // Senegal
    SRB = 688,  // Serbia
    SYC = 690,  // Seychelles
    SLE = 694,  // Sierra Leone
    SGP = 702,  // Singapore
    SXM = 534,  // Sint Maarten (Dutch part)
    SVK = 703,  // Slovakia
    SVN = 705,  // Slovenia
    SLB = 90,   // Solomon Islands
    SOM = 706,  // Somalia
    ZAF = 710,  // South Africa
    SGS = 239,  // South Georgia and the South Sandwich Islands
    SSD = 728,  // South Sudan
    ESP = 724,  // Spain
    LKA = 144,  // Sri Lanka
    PSE = 275,  // State of Palestine
    SDN = 729,  // Sudan
    SUR = 740,  // Suriname
    SJM = 744,  // Svalbard and Jan Mayen Islands
    SWE = 752,  // Sweden
    CHE = 756,  // Switzerland
    SYR = 760,  // Syrian Arab Republic
    TJK = 762,  // Tajikistan
    THA = 764,  // Thailand
    TLS = 626,  // Timor-Leste
    TGO = 768,  // Togo
    TKL = 772,  // Tokelau
    TON = 776,  // Tonga
    TTO = 780,  // Trinidad and Tobago
    TUN = 788,  // Tunisia
    TUR = 792,  // Türkiye
    TKM = 795,  // Turkmenistan
    TCA = 796,  // Turks and Caicos Islands
    TUV = 798,  // Tuvalu
    UGA = 800,  // Uganda
    UKR = 804,  // Ukraine
    ARE = 784,  // United Arab Emirates
    GBR = 826,  // United Kingdom of Great Britain and Northern Ireland
    TZA = 834,  // United Republic of Tanzania
    UMI = 581,  // United States Minor Outlying Islands
    USA = 840,  // United States of America
    VIR = 850,  // United States Virgin Islands
    URY = 858,  // Uruguay
    UZB = 860,  // Uzbekistan
    VUT = 548,  // Vanuatu
    VEN = 862,  // Venezuela (Bolivarian Republic of)
    VNM = 704,  // Viet Nam
    WLF = 876,  // Wallis and Futuna Islands
    ESH = 732,  // Western Sahara
    YEM = 887,  // Yemen
    ZMB = 894,  // Zambia
    ZWE = 716   // Zimbabwe
};

Certainly! Here's an enumeration in C++ using the provided ISO2 country codes and their corresponding numeric values:

```cpp
enum class Countries_ISO2 {
    AF = 4,    // Afghanistan
    AL = 8,    // Albania
    DZ = 12,   // Algeria
    AS = 16,   // American Samoa
    AD = 20,   // Andorra
    AO = 24,   // Angola
    AI = 660,  // Anguilla
    AQ = 10,   // Antarctica
    AG = 28,   // Antigua and Barbuda
    AR = 32,   // Argentina
    AM = 51,   // Armenia
    AW = 533,  // Aruba
    AU = 36,   // Australia
    AT = 40,   // Austria
    AZ = 31,   // Azerbaijan
    BS = 44,   // Bahamas
    BH = 48,   // Bahrain
    BD = 50,   // Bangladesh
    BB = 52,   // Barbados
    BY = 112,  // Belarus
    BE = 56,   // Belgium
    BZ = 84,   // Belize
    BJ = 204,  // Benin
    BM = 60,   // Bermuda
    BT = 64,   // Bhutan
    BO = 68,   // Bolivia
    BQ = 535,  // Bonaire, Sint Eustatius and Saba
    BA = 70,   // Bosnia and Herzegovina
    BW = 72,   // Botswana
    BV = 74,   // Bouvet Island
    BR = 76,   // Brazil
    IO = 86,   // British Indian Ocean Territory
    BN = 96,   // Brunei Darussalam
    BG = 100,  // Bulgaria
    BF = 854,  // Burkina Faso
    BI = 108,  // Burundi
    CV = 132,  // Cabo Verde
    KH = 116,  // Cambodia
    CM = 120,  // Cameroon
    CA = 124,  // Canada
    KY = 136,  // Cayman Islands
    CF = 140,  // Central African Republic
    TD = 148,  // Chad
    CL = 152,  // Chile
    CN = 156,  // China
    CX = 162,  // Christmas Island
    CC = 166,  // Cocos (Keeling) Islands
    CO = 170,  // Colombia
    KM = 174,  // Comoros
    CD = 180,  // Congo (the Democratic Republic of the)
    CG = 178,  // Congo (the)
    CK = 184,  // Cook Islands
    CR = 188,  // Costa Rica
    HR = 191,  // Croatia
    CU = 192,  // Cuba
    CW = 531,  // Curaçao
    CY = 196,  // Cyprus
    CZ = 203,  // Czechia
    CI = 384,  // Côte d'Ivoire
    DK = 208,  // Denmark
    DJ = 262,  // Djibouti
    DM = 212,  // Dominica
    DO = 214,  // Dominican Republic
    EC = 218,  // Ecuador
    EG = 818,  // Egypt
    SV = 222,  // El Salvador
    GQ = 226,  // Equatorial Guinea
    ER = 232,  // Eritrea
    EE = 233,  // Estonia
    SZ = 748,  // Eswatini
    ET = 231,  // Ethiopia
    FK = 238,  // Falkland Islands
    FO = 234,  // Faroe Islands
    FJ = 242,  // Fiji
    FI = 246,  // Finland
    FR = 250,  // France
    GF = 254,  // French Guiana
    PF = 258,  // French Polynesia
    TF = 260,  // French Southern Territories
    GA = 266,  // Gabon
    GM = 270,  // Gambia
    GE = 268,  // Georgia
    DE = 276,  // Germany
    GH = 288,  // Ghana
    GI = 292,  // Gibraltar
    GR = 300,  // Greece
    GL = 304,  // Greenland
    GD = 308,  // Grenada
    GP = 312,  // Guadeloupe
    GU = 316,  // Guam
    GT = 320,  // Guatemala
    GG = 831,  // Guernsey
    GN = 324,  // Guinea
    GW = 624,  // Guinea-Bissau
    GY = 328,  // Guyana
    HT = 332,  // Haiti
    HM = 334,  // Heard Island and McDonald Islands
    VA = 336,  // Holy See
    HN = 340,  // Honduras
    HK = 344,  // Hong Kong
    HU = 348,  // Hungary
    IS = 352,  // Iceland
    IN = 356,  // India
    ID = 360,  // Indonesia
    IR = 364,  // Iran
    IQ = 368,  // Iraq
    IE = 372,  // Ireland
    IM = 833,  // Isle of Man
    IL = 376,  // Israel
    IT = 380,  // Italy
    JM = 388,  // Jamaica
    JP = 392,  // Japan
    JE = 832,  // Jersey
    JO = 400,  // Jordan
    KZ = 398,  // Kazakhstan
    KE = 404,  // Kenya
    KI = 296,  // Kiribati
    KP = 408,  // Korea (the Democratic People's Republic of)
    KR = 410,  // Korea (the Republic of)
    KW = 414,  // Kuwait
    KG = 417,  // Kyrgyzstan
    LA = 418,  // Lao People's Democratic Republic
    LV = 428,  // Latvia
    LB = 422,  // Lebanon
    LS = 426,  // Lesotho
    LR = 430,  // Liberia
    LY = 434,  // Libya
    LI = 438,  // Liechtenstein
    LT = 440,  // Lithuania
    LU = 442,  // Luxembourg
    MO = 446,  // Macao
    MG = 450,  // Madagascar
    MW = 454,  // Malawi
    MY = 458,  // Malaysia
    MV = 462,  // Maldives
    ML = 466,  // Mali
    MT = 470,  // Malta
    MH = 584,  // Marshall Islands
    MQ = 474,  // Martinique
    MR = 478,  // Mauritania
    MU = 480,  // Mauritius
    YT = 175,  // Mayotte
    MX = 484,  // Mexico
    FM = 583,  // Micronesia
    MD = 498,  // Moldova
    MC = 492,  // Monaco
    MN = 496,  // Mongolia
    ME = 499,  // Montenegro
    MS = 500,  // Montserrat
    MA = 504,  // Morocco
    MZ = 508,  // Mozambique
    MM = 104,  // Myanmar
    NA = 516,  // Namibia
    NR = 520,  // Nauru
    NP = 524,  // Nepal
    NL = 528,  // Netherlands
    NC = 540,  // New Caledonia
    NZ = 554,  // New Zealand
    NI = 558,  // Nicaragua
    NE = 562,  // Niger
    NG = 566,  // Nigeria
    NU = 570,  // Niue
    NF = 574,  // Norfolk Island
    MP = 580,  // Northern Mariana Islands
    NO = 578,  // Norway
    OM = 512,  // Oman
    PK = 586,  // Pakistan
    PW = 585,  // Palau
    PS = 275,  // Palestine, State of
    PA = 591,  // Panama
    PG = 598,  // Papua New Guinea
    PY = 600,  // Paraguay
    PE = 604,  // Peru
    PH = 608,  // Philippines
    PN = 612,  // Pitcairn
    PL = 616,  // Poland
    PT = 620,  // Portugal
    PR = 630,  // Puerto Rico
    QA = 634,  // Qatar
    MK = 807,  // Republic of North Macedonia
    RO = 642,  // Romania
    RU = 643,  // Russian Federation
    RW = 646,  // Rwanda
    RE = 638,  // Réunion
    BL = 652,  // Saint Barthélemy
    SH = 654,  // Saint Helena, Ascension and Tristan da Cunha
    KN = 659,  // Saint Kitts and Nevis
    LC = 662,  // Saint Lucia
    MF = 663,  // Saint Martin (French part)
    PM = 666,  // Saint Pierre and Miquelon
    VC = 670,  // Saint Vincent and the Grenadines
    WS = 882,  // Samoa
    SM = 674,  // San Marino
    ST = 678,  // Sao Tome and Principe
    SA = 682,  // Saudi Arabia
    SN = 686,  // Senegal
    RS = 688,  // Serbia
    SC = 690,  // Seychelles
    SL = 694,  // Sierra Leone
    SG = 702,  // Singapore
    SX = 534,  // Sint Maarten (Dutch part)
    SK = 703,  // Slovakia
    SI = 705,  // Slovenia
    SB = 90,   // Solomon Islands
    SO = 706,  // Somalia
    ZA = 710,  // South Africa
    GS = 239,  // South Georgia and the South Sandwich Islands
    SS = 728,  // South Sudan
    ES = 724,  // Spain
    LK = 144,  // Sri Lanka
    SD = 729,  // Sudan
    SR = 740,  // Suriname
    SJ = 744,  // Svalbard and Jan Mayen
    SE = 752,  // Sweden
    CH = 756,  // Switzerland
    SY = 760,  // Syrian Arab Republic
    TW = 158,  // Taiwan (Province of China)
    TJ = 762,  // Tajikistan
    TZ = 834,  // Tanzania, United Republic of
    TH = 764,  // Thailand
    TL = 626,  // Timor-Leste
    TG = 768,  // Togo
    TK = 772,  // Tokelau
    TO = 776,  // Tonga
    TT = 780,  // Trinidad and Tobago
    TN = 788,  // Tunisia
    TR = 792,  // Turkey
    TM = 795,  // Turkmenistan
    TC = 796,  // Turks and Caicos Islands
    TV = 798,  // Tuvalu
    UG = 800,  // Uganda
    UA = 804,  // Ukraine
    AE = 784,  // United Arab Emirates
    GB = 826,  // United Kingdom of Great Britain and Northern Ireland
    UM = 581,  // United States Minor Outlying Islands
    US = 840,  // United States of America
    UY = 858,  // Uruguay
    UZ = 860,  // Uzbekistan
    VU = 548,  // Vanuatu
    VE = 862,  // Venezuela (Bolivarian Republic of)
    VN = 704,  // Viet Nam
    VG = 92,   // Virgin Islands (British)
    VI = 850,  // Virgin Islands (U.S.)
    WF = 876,  // Wallis and Futuna
    EH = 732,  // Western Sahara
    YE = 887,  // Yemen
    ZM = 894,  // Zambia
    ZW = 716,  // Zimbabwe
    AX = 248   // Åland Islands
};



enum class Countries {
    AFGHANISTAN = 4,
    ALAND_ISLANDS = 248,
    ALBANIA = 8,
    ALGERIA = 12,
    AMERICAN_SAMOA = 16,
    ANDORRA = 20,
    ANGOLA = 24,
    ANGUILLA = 660,
    ANTARCTICA = 10,
    ANTIGUA_AND_BARBUDA = 28,
    ARGENTINA = 32,
    ARMENIA = 51,
    ARUBA = 533,
    AUSTRALIA = 36,
    AUSTRIA = 40,
    AZERBAIJAN = 31,
    BAHAMAS = 44,
    BAHRAIN = 48,
    BANGLADESH = 50,
    BARBADOS = 52,
    BELARUS = 112,
    BELGIUM = 56,
    BELIZE = 84,
    BENIN = 204,
    BERMUDA = 60,
    BHUTAN = 64,
    BOLIVIA = 68,
    BONAIRE_SINT_EUSTATIUS_AND_SABA = 535,
    BOSNIA_AND_HERZEGOVINA = 70,
    BOTSWANA = 72,
    BOUVET_ISLAND = 74,
    BRAZIL = 76,
    BRITISH_INDIAN_OCEAN_TERRITORY = 86,
    BRITISH_VIRGIN_ISLANDS = 92,
    BRUNEI_DARUSSALAM = 96,
    BULGARIA = 100,
    BURKINA_FASO = 854,
    BURUNDI = 108,
    CABO_VERDE = 132,
    CAMBODIA = 116,
    CAMEROON = 120,
    CANADA = 124,
    CAYMAN_ISLANDS = 136,
    CENTRAL_AFRICAN_REPUBLIC = 140,
    CHAD = 148,
    CHILE = 152,
    CHINA = 156,
    CHINA_HONG_KONG_SAR = 344,
    CHINA_MACAO_SAR = 446,
    CHRISTMAS_ISLAND = 162,
    COCOS_KEELING_ISLANDS = 166,
    COLOMBIA = 170,
    COMOROS = 174,
    CONGO = 178,
    COOK_ISLANDS = 184,
    COSTA_RICA = 188,
    COTE_DIVOIRE = 384,
    CROATIA = 191,
    CUBA = 192,
    CURACAO = 531,
    CYPRUS = 196,
    CZECHIA = 203,
    DEMOCRATIC_PEOPLES_REPUBLIC_OF_KOREA = 408,
    DEMOCRATIC_REPUBLIC_OF_THE_CONGO = 180,
    DENMARK = 208,
    DJIBOUTI = 262,
    DOMINICA = 212,
    DOMINICAN_REPUBLIC = 214,
    ECUADOR = 218,
    EGYPT = 818,
    EL_SALVADOR = 222,
    EQUATORIAL_GUINEA = 226,
    ERITREA = 232,
    ESTONIA = 233,
    ESWATINI = 748,
    ETHIOPIA = 231,
    FALKLAND_ISLANDS_MALVINAS = 238,
    FAROE_ISLANDS = 234,
    FIJI = 242,
    FINLAND = 246,
    FRANCE = 250,
    FRENCH_GUIANA = 254,
    FRENCH_POLYNESIA = 258,
    FRENCH_SOUTHERN_TERRITORIES = 260,
    GABON = 266,
    GAMBIA = 270,
    GEORGIA = 268,
    GERMANY = 276,
    GHANA = 288,
    GIBRALTAR = 292,
    GREECE = 300,
    GREENLAND = 304,
    GRENADA = 308,
    GUADELOUPE = 312,
    GUAM = 316,
    GUATEMALA = 320,
    GUERNSEY = 831,
    GUINEA = 324,
    GUINEA_BISSAU = 624,
    GUYANA = 328,
    HAITI = 332,
    HEARD_ISLAND_AND_MCDONALD_ISLANDS = 334,
    HOLY_SEE = 336,
    HONDURAS = 340,
    HUNGARY = 348,
    ICELAND = 352,
    INDIA = 356,
    INDONESIA = 360,
    IRAN = 364,
    IRAQ = 368,
    IRELAND = 372,
    ISLE_OF_MAN = 833,
    ISRAEL = 376,
    ITALY = 380,
    JAMAICA = 388,
    JAPAN = 392,
    JERSEY = 832,
    JORDAN = 400,
    KAZAKHSTAN = 398,
    KENYA = 404,
    KIRIBATI = 296,
    KUWAIT = 414,
    KYRGYZSTAN = 417,
    LAO_PEOPLES_DEMOCRATIC_REPUBLIC = 418,
    LATVIA = 428,
    LEBANON = 422,
    LESOTHO = 426,
    LIBERIA = 430,
    LIBYA = 434,
    LIECHTENSTEIN = 438,
    LITHUANIA = 440,
    LUXEMBOURG = 442,
    MADAGASCAR = 450,
    MALAWI = 454,
    MALAYSIA = 458,
    MALDIVES = 462,
    MALI = 466,
    MALTA = 470,
    MARSHALL_ISLANDS = 584,
    MARTINIQUE = 474,
    MAURITANIA = 478,
    MAURITIUS = 480,
    MAYOTTE = 175,
    MEXICO = 484,
    MICRONESIA = 583,
    MONACO = 492,
    MONGOLIA = 496,
    MONTENEGRO = 499,
    MONTSERRAT = 500,
    MOROCCO = 504,
    MOZAMBIQUE = 508,
    MYANMAR = 104,
    NAMIBIA = 516,
    NAURU = 520,
    NEPAL = 524,
    NETHERLANDS = 528,
    NEW_CALEDONIA = 540,
    NEW_ZEALAND = 554,
    NICARAGUA = 558,
    NIGER = 562,
    NIGERIA = 566,
    NIUE = 570,
    NORFOLK_ISLAND = 574,
    NORTH_MACEDONIA = 807,
    NORTHERN_MARIANA_ISLANDS = 580,
    NORWAY = 578,
    OMAN = 512,
    PAKISTAN = 586,
    PALAU = 585,
    PANAMA = 591,
    PAPUA_NEW_GUINEA = 598,
    PARAGUAY = 600,
    PERU = 604,
    PHILIPPINES = 608,
    PITCAIRN = 612,
    POLAND = 616,
    PORTUGAL = 620,
    PUERTO_RICO = 630,
    QATAR = 634,
    REPUBLIC_OF_KOREA = 410,
    REPUBLIC_OF_MOLDOVA = 498,
    REUNION = 638,
    ROMANIA = 642,
    RUSSIAN_FEDERATION = 643,
    RWANDA = 646,
    SAINT_BARTHELEMY = 652,
    SAINT_HELENA = 654,
    SAINT_KITTS_AND_NEVIS = 659,
    SAINT_LUCIA = 662,
    SAINT_MARTIN_FRENCH_PART = 663,
    SAINT_PIERRE_AND_MIQUELON = 666,
    SAINT_VINCENT_AND_THE_GRENADINES = 670,
    SAMOA = 882,
    SAN_MARINO = 674,
    SAO_TOME_AND_PRINCIPE = 678,
    SAUDI_ARABIA = 682,
    SENEGAL = 686,
    SERBIA = 688,
    SEYCHELLES = 690,
    SIERRA_LEONE = 694,
    SINGAPORE = 702,
    SINT_MAARTEN_DUTCH_PART = 534,
    SLOVAKIA = 703,
    SLOVENIA = 705,
    SOLOMON_ISLANDS = 90,
    SOMALIA = 706,
    SOUTH_AFRICA = 710,
    SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS = 239,
    SOUTH_SUDAN = 728,
    SPAIN = 724,
    SRI_LANKA = 144,
    STATE_OF_PALESTINE = 275,
    SUDAN = 729
    SURINAME = 740,
    SVALBARD_AND_JAN_MAYEN_ISLANDS = 744,
    SWEDEN = 752,
    SWITZERLAND = 756,
    SYRIAN_ARAB_REPUBLIC = 760,
    TAJIKISTAN = 762,
    THAILAND = 764,
    TIMOR_LESTE = 626,
    TOGO = 768,
    TOKELAU = 772,
    TONGA = 776,
    TRINIDAD_AND_TOBAGO = 780,
    TUNISIA = 788,
    TURKEY = 792,
    TURKMENISTAN = 795,
    TURKS_AND_CAICOS_ISLANDS = 796,
    TUVALU = 798,
    UGANDA = 800,
    UKRAINE = 804,
    UNITED_ARAB_EMIRATES = 784,
    UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND = 826,
    UNITED_REPUBLIC_OF_TANZANIA = 834,
    UNITED_STATES_MINOR_OUTLYING_ISLANDS = 581,
    UNITED_STATES_OF_AMERICA = 840,
    UNITED_STATES_VIRGIN_ISLANDS = 850,
    URUGUAY = 858,
    UZBEKISTAN = 860,
    VANUATU = 548,
    VENEZUELA_BOLIVARIAN_REPUBLIC_OF = 862,
    VIET_NAM = 704,
    WALLIS_AND_FUTUNA_ISLANDS = 876,
    WESTERN_SAHARA = 732,
    YEMEN = 887,
    ZAMBIA = 894,
    ZIMBABWE = 716
};